export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_USER = 'GET_USER';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const CODE_SUSCCESSFUL = 'CODE_SUSCCESSFUL';
export const CODE_ERROR = 'CODE_ERROR';